apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: legal-ref-api
  namespace: legal-ref
spec:
  selector:
    matchLabels:
      app: legal-ref-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
